// action
export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const GET_FULL_ARTICLE = "GET_FULL_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";

// mutation
export const ADD_ARTICLE = "ADD_ARTICLE";
export const UPDATE_ARTICLE_LOCALLY = "UPDATE_ARTICLE_LOCALLY";
